import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import EBAnimation from "./EB_Animation.gif";
import photo1 from "./photos/colour/Erin-and-Benoit-October-10th-2022-5 copy.jpg";
import photo2 from "./photos/colour/Erin-and-Benoit-October-10th-2022-10 copy.jpg";
import photo3 from "./photos/colour/Erin-and-Benoit-October-10th-2022-14 copy.jpg";
import photo4 from "./photos/colour/Erin-and-Benoit-October-10th-2022-15 copy.jpg";
import photo5 from "./photos/colour/Erin-and-Benoit-October-10th-2022-17 copy.jpg";
import photo6 from "./photos/colour/Erin-and-Benoit-October-10th-2022-22 copy.jpg";
import photo7 from "./photos/colour/Erin-and-Benoit-October-10th-2022-24 copy.jpg";
import photo8 from "./photos/colour/Erin-and-Benoit-October-10th-2022-29 copy.jpg";
import photo9 from "./photos/colour/Erin-and-Benoit-October-10th-2022-32 copy.jpg";
import photo10 from "./photos/colour/Erin-and-Benoit-October-10th-2022-33 copy.jpg";
import photo11 from "./photos/colour/Erin-and-Benoit-October-10th-2022-34 copy.jpg";
import photo12 from "./photos/colour/Erin-and-Benoit-October-10th-2022-36 copy.jpg";
import photo13 from "./photos/colour/Erin-and-Benoit-October-10th-2022-38 copy.jpg";
import selfie1 from "./photos/1393660_10151956705209044_1500732883_n.jpeg";
import selfie2 from "./photos/1545102_10152126381159044_1383338928_n.jpeg";
import selfie3 from "./photos/1556317_10152207639034044_947552684_o.jpeg";
import selfie4 from "./photos/1932760_10152022418761571_8057865125272373578_o.jpeg";
import selfie5 from "./photos/10402832_10152406665794477_3195916928990505768_n.jpeg";
import selfie6 from "./photos/10462979_10152439689464477_3150465525488740842_n.jpeg";
import selfie7 from "./photos/10659151_10152802366934044_8416236795462307694_n.jpeg";
import selfie8 from "./photos/10700772_10152764280329044_2181995657480727987_o.jpeg";
import selfie9 from "./photos/10888369_10153032807314044_8083078317882725055_n.jpeg";
import selfie10 from "./photos/12063841_10153670961004044_2676112754234180775_n.jpeg";
import selfie11 from "./photos/12439451_10154711035518332_6320943471325198537_n.jpeg";
import selfie12 from "./photos/15626391_10154904006034044_8757797929371504982_o.jpeg";
import selfie13 from "./photos/16586890_10155061560484044_3744138414737439486_o.jpeg";
import selfie14 from "./photos/22459540_10155833111539044_456613674923116_o.jpeg";
import selfie15 from "./photos/137201047_10159003808099044_6028878272001954561_n.jpeg";

// Create lists of all the photos that we can then loop over
// furthe down in the code. The images will be shown in the
// order that they are listed here.
const images = {
  photos: [
    photo1,
    photo2,
    photo3,
    photo4,
    photo5,
    photo6,
    photo7,
    photo8,
    photo9,
    photo10,
    photo11,
    photo12,
    photo13,
  ],
  selfies: [
    selfie1,
    selfie2,
    selfie3,
    selfie4,
    selfie5,
    selfie6,
    selfie7,
    selfie8,
    selfie9,
    selfie10,
    selfie11,
    selfie12,
    selfie13,
    selfie14,
    selfie15,
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Erin & Benoit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header className={styles.Header}>
        <nav>
          <ul>
            <li>
              <a href="#">Something</a>
            </li>
            <li>
              <a href="#">Something</a>
            </li>
            <li>
              <a href="#">Something</a>
            </li>
            <li>
              <a href="#">Something</a>
            </li>
            <li>
              <a href="#">Something</a>
            </li>
          </ul>
        </nav>
      </header>
      <main>
        <section className={styles.Hero}>
          <div className={styles.HeroContent}>
            <Image
              src={EBAnimation}
              alt="The letters E and B. Animated flowers appear."
              width={1668 / 2}
              height={2388 / 2}
            />
            <div className={styles.HeroText}>
              <p>Erin & Benoit &middot; 2023-00-00</p>
              <p>Please join us out in the boonies, to celebrate our love!</p>
            </div>
          </div>
        </section>
        {images.selfies.map((image) => (
          <Image
            key={image.src}
            {...image}
            alt=""
            width={500}
            height={500 / (image.width / image.height)}
          />
        ))}
        {images.photos.map((image) => (
          <Image
            key={image.src}
            {...image}
            alt=""
            width={image.width / 4}
            height={image.height / 4}
          />
        ))}
        <p>Please join us out in the boonies, to celebrate our love!</p>
        <p>Save the date calendar buttonTiming info</p>
        <p>
          Ceremony 4pm sharp, followed by cocktails. Dinner at 6pm, followed by
          dance party.
        </p>
        <p>Venue Location: 915 Chem. du Mont-des-Cascades Cantley, Q</p>
        <p>get directions button</p>
        <p>
          Our venue is a covered outdoor patio, however guests may want to go
          out onto the grass for a photos during cocktail hour. Please be aware
          of your shoes!
        </p>
        <p>Accommodations:</p>
        <p>
          Holiday Inn Gatineau
          <br />7 boulevard du Casino
          <br />
          Gatineau, QC
          <br />
        </p>
        <p>
          To book using group discount:
          <br />
          call 8195252255 or Book Online
        </p>
        <p>
          Group discount code “ERC”
          <br />
          Group discount extended 3 days post/prior June 3<br />
          Please book accommodations asap to ensure your stay!
        </p>
        <p>
          Other hotels to consider, closer to the venue:
          https://www.motelchelsea.com/
          <br />
          https://wakefieldmill.com/
          <br />
          https://wakefieldinn.ca/https://lebellevue.ca/
        </p>
        <p>
          The venue is out in the boonies, down winding dirt roads. There will
          be a service available to bring you & your car home for a fee, if
          desired! Please, no drinking & driving.{" "}
        </p>
        <p>
          Parking info: There is ample parking at the venue, however we will be
          providing a shuttle from the Holiday Inn Gatineau, for those wishing
          to partake in the bar.
        </p>
        <p>Attire - link to pinterest</p>
        <p>RSVP</p>
        <p>Shuttles will leave venue at _ & _</p>
        <p>
          Shuttles will be making a stop at Casino Lac Leamy for those wishing
          to continue the party into the wee hours.{" "}
        </p>
        <h3>FAQ</h3>
        <p>
          What should I wear? We want you to be comfortable. The venue is
          outdoors, but if the weather is bad there are rain curtains and
          heaters. Dress accordingly! We’ve put together a lookbook on pinterest
          if you want some ideas. We suggest anything light & bright to kick off
          summer! The weather for June 3 in 2022 was 22 during the day and 15 at
          night.
        </p>
        <p>
          Gifts? We have most things we need for life and love. If you want to
          give us a gift, we can always use cash gifts as we look for a new
          home.
        </p>
        <p>
          Are kids invited? Unfortunately due to numbers, we cannot accommodate
          kids unless specified.
        </p>
        <p>
          Do I get a +1? Unfortunately due to numbers, we cannot accommodate
          dates unless specified.
        </p>
        <p>
          I don’t want to take the shuttle, options? Taxi, Ride ProgramWhere do
          I park? There is ample parking at the venue, once you arrive at Golf
          Mont Cascades you will see the clubhouse, and a barn. The parking is
          directly behind the barn!
        </p>
        Gallery
      </main>
    </>
  );
}
