import Image from "next/image";
import theMorningAfter from "./the-morning-after.svg";
import styles from "../styles/TheMorningAfter.module.scss";

export default function TheMorningAfter() {
  return (  
   
<div className={styles.TheMorningAfter}>
<Image src={theMorningAfter} alt="The Morning After" />
  
<Head>
  <title>Erin & Benoit</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="icon" href="/icon.svg" type="image/svg+xml" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link
       rel="preconnect"
       href="https://fonts.gstatic.com"
       crossOrigin=""
     />
     <link
       href="https://fonts.googleapis.com/css2?family=Lexend:wght@500&family=Raleway:wght@300;400;500;600&display=swap"
       rel="stylesheet"
     />
</Head>
  
  <main>
    <p>
      Thanks so much for travelling to our wedding ♥
    </p>
    <p>
      We hope you can join us for a cup of coffee, and some pastries before you go!
    </p>

    <h1>9-11am</h1>

    <p>
      Holiday Inn Gatineau
    </p>
    <p>
      7 Bd du Casino, Gatineau, QC
    </p>

    <p>
      <a href="https://forms.gle/7Uo9Rw1iEhwLGbfw7">RVSP</a>
    </p>

    <p>
      Follow signs for Erin & Benoit
    </p>
    
  </main>
  );
}
